name: 'microsoft_ads_source'
version: '0.5.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
models:
  microsoft_ads_source:
    +schema: stg_microsoft_ads
    +materialized: table
vars:
  microsoft_ads_source:
    account_history: "{{ source('microsoft_ads','account_history') }}"
    ad_group_history: "{{ source('microsoft_ads','ad_group_history') }}"
    ad_history: "{{ source('microsoft_ads','ad_history') }}"
    ad_performance_daily_report: "{{ source('microsoft_ads','ad_performance_daily_report') }}"
    campaign_history: "{{ source('microsoft_ads','campaign_history') }}"
