name: 'microsoft_ads_source_integration_tests'
version: '0.6.0'
profile: 'integration_tests'
config-version: 2

vars: 
  microsoft_ads_schema: microsoft_ads_source_integration_tests
  microsoft_ads_account_history_identifier: "microsoft_ads_account_history_data"
  microsoft_ads_account_daily_report_identifier: "microsoft_ads_account_performance_daily_report_data"
  microsoft_ads_ad_group_history_identifier: "microsoft_ads_ad_group_history_data"
  microsoft_ads_ad_group_daily_report_identifier: "microsoft_ads_ad_group_performance_daily_report_data"
  microsoft_ads_ad_history_identifier: "microsoft_ads_ad_history_data"
  microsoft_ads_ad_daily_report_identifier: "microsoft_ads_ad_performance_daily_report_data"
  microsoft_ads_campaign_history_identifier: "microsoft_ads_campaign_history_data"
  microsoft_ads_campaign_daily_report_identifier: "microsoft_ads_campaign_performance_daily_report_data"
  microsoft_ads_keyword_history_identifier: "microsoft_ads_keyword_history_data"
  microsoft_ads_keyword_daily_report_identifier: "microsoft_ads_keyword_performance_daily_report_data"
  microsoft_ads_search_daily_report_identifier: "microsoft_ads_search_performance_daily_report_data"

seeds:
  microsoft_ads_source_integration_tests:
    +column_types:
      id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      account_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      ad_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      keyword_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      last_modified_time: "timestamp"
      modified_time: "timestamp"
      spend: "float"
      impressions: "integer"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
