{% macro get_geographic_daily_report_columns() %}

{% set columns = [
    {"name": "_fivetran_id", "datatype": dbt.type_string()},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "absolute_top_impression_rate_percent", "datatype": dbt.type_float()},
    {"name": "account_id", "datatype": dbt.type_int()},
    {"name": "account_name", "datatype": dbt.type_string()},
    {"name": "account_number", "datatype": dbt.type_string()},
    {"name": "account_status", "datatype": dbt.type_string()},
    {"name": "ad_distribution", "datatype": dbt.type_string()},
    {"name": "ad_group_id", "datatype": dbt.type_int()},
    {"name": "ad_group_name", "datatype": dbt.type_string()},
    {"name": "ad_group_status", "datatype": dbt.type_string()},
    {"name": "all_conversion_rate", "datatype": dbt.type_float()},
    {"name": "all_conversions", "datatype": dbt.type_int()},
    {"name": "all_conversions_qualified", "datatype": dbt.type_float()},
    {"name": "all_cost_per_conversion", "datatype": dbt.type_float()},
    {"name": "all_return_on_ad_spend", "datatype": dbt.type_float()},
    {"name": "all_revenue", "datatype": dbt.type_float()},
    {"name": "all_revenue_per_conversion", "datatype": dbt.type_float()},
    {"name": "assists", "datatype": dbt.type_int()},
    {"name": "average_cpc", "datatype": dbt.type_float()},
    {"name": "average_cpm", "datatype": dbt.type_float()},
    {"name": "average_position", "datatype": dbt.type_float()},
    {"name": "base_campaign_id", "datatype": dbt.type_int()},
    {"name": "bid_match_type", "datatype": dbt.type_string()},
    {"name": "campaign_id", "datatype": dbt.type_int()},
    {"name": "campaign_name", "datatype": dbt.type_string()},
    {"name": "campaign_status", "datatype": dbt.type_string()},
    {"name": "campaign_type", "datatype": dbt.type_string()},
    {"name": "city", "datatype": dbt.type_string()},
    {"name": "clicks", "datatype": dbt.type_int()},
    {"name": "conversion_rate", "datatype": dbt.type_float()},
    {"name": "conversions", "datatype": dbt.type_int()},
    {"name": "conversions_qualified", "datatype": dbt.type_float()},
    {"name": "cost_per_conversion", "datatype": dbt.type_float()},
    {"name": "country", "datatype": dbt.type_string()},
    {"name": "county", "datatype": dbt.type_string()},
    {"name": "ctr", "datatype": dbt.type_float()},
    {"name": "currency_code", "datatype": dbt.type_string()},
    {"name": "date", "datatype": "date"},
    {"name": "delivered_match_type", "datatype": dbt.type_string()},
    {"name": "device_os", "datatype": dbt.type_string()},
    {"name": "device_type", "datatype": dbt.type_string()},
    {"name": "goal", "datatype": dbt.type_string()},
    {"name": "goal_type", "datatype": dbt.type_string()},
    {"name": "impressions", "datatype": dbt.type_int()},
    {"name": "language", "datatype": dbt.type_string()},
    {"name": "location_id", "datatype": dbt.type_int()},
    {"name": "location_type", "datatype": dbt.type_string()},
    {"name": "metro_area", "datatype": dbt.type_string()},
    {"name": "most_specific_location", "datatype": dbt.type_string()},
    {"name": "neighborhood", "datatype": dbt.type_string()},
    {"name": "network", "datatype": dbt.type_string()},
    {"name": "postal_code", "datatype": dbt.type_string()},
    {"name": "radius", "datatype": dbt.type_int()},
    {"name": "return_on_ad_spend", "datatype": dbt.type_float()},
    {"name": "revenue", "datatype": dbt.type_float()},
    {"name": "revenue_per_conversion", "datatype": dbt.type_float()},
    {"name": "spend", "datatype": dbt.type_float()},
    {"name": "state", "datatype": dbt.type_string()},
    {"name": "top_impression_rate_percent", "datatype": dbt.type_float()},
    {"name": "top_vs_other", "datatype": dbt.type_string()},
    {"name": "view_through_conversions", "datatype": dbt.type_int()},
    {"name": "view_through_revenue", "datatype": dbt.type_float()}
] %}

{{ microsoft_ads_add_pass_through_columns(base_columns=columns, pass_through_fields=var('microsoft_ads__geographic_passthrough_metrics'), except_fields=['conversions_qualified', 'conversions', 'revenue', 'all_conversions_qualified', 'all_conversions', 'all_revenue']) }}

{{ return(columns) }}

{% endmacro %}